'use client'
import React, { useEffect } from 'react'
import Header from './components/header'
import Main from './components/main'
import { useDispatch, useSelector } from 'react-redux';
import { userExists, userNotExists } from '@/redux/reducers/auth';
import axios from 'axios';
import { SocketProvider } from '../socket';

// export const metadata = {
//     title: "Home",
//     description: "Generated by create next app",
//   };

const page = () => {

const {user,loader}=useSelector((state)=>state.auth);
const dispatch=useDispatch();

useEffect(()=>{
  axios.get('http://localhost:3001/api/v1/user/me',{withCredentials:true})
  .then(({data})=>dispatch(userExists(data.user)))
  .catch((err)=> dispatch(userNotExists()));
},[dispatch])

  return (
    <>
<Header/>

<SocketProvider>
<Main user={user}/>
</SocketProvider>
    
    </>
  )
}

export default page