import React from 'react'
import ChatList from './components/chatList';

export const metadata = {
    title: "Chat",
    description: "Generated by create next app",
  };

const page = () => {
  return (
    <>
    <ChatList/>
    
    Hello
    
    </>
  )
}

export default page