
'use client'
import { Inter } from "next/font/google";
import store from "../redux/store";
import {Provider} from 'react-redux'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import {ToastContainer} from './nexttoast'
import 'react-toastify/dist/ReactToastify.css';
const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider store={store}>
      
        <AppRouterCacheProvider>
      
  
        {children}
        </AppRouterCacheProvider>
        </Provider>
      <ToastContainer/>
        </body>
    </html>
  );
}
