import React from 'react'
import Link from 'next/link';



export const metadata = {
    title: "Not Found",
    description: "Generated by create next app",
  };

const NotFound = () => {
    

    <title>NOT Found Page</title>
  return (
    <>
    <h1>ooopps</h1>
    <h2>
      page Not Found
    </h2>
    <p>Back to the<Link href='/'>Home</Link> </p>
     </>
  )
}

export default NotFound