
import Login from './components/login'

export const metadata = {
    title: "Login",
    description: "Generated by create next app",
  };
const page = () => {

  return (
    <>
    
  

    <Login />
    
    </>
  )
}

export default page