


import React from 'react'


import GroupPage from './components/groupPage';



export const metadata = {
    title: "Group",
    description: "Generated by create next app",
  };


const Group = () => {

return(
  <GroupPage/>
    
  
)}

export default Group