import React from "react";
import AdminLayout from "./components/adminLayout";
import AppBar from "./components/appBar";
import Charts from "./components/charts";
import { Container, Stack } from "@mui/material";
import Widgets from "./components/widget";
import {
  Group as GroupIcon,
  Message,
  Person as PersonIcon,
} from "@mui/icons-material";
export const metadata = {
  title: "DashBoard",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <AdminLayout>
      <Container>
        <AppBar />
        <Stack>
          <Charts />
        </Stack>
        <Stack
          direction={{ xs: "column", sm: "row" }}
          marginTop={"1rem"}
          spacing="1rem"
          justifyContent="space-between"
          alignItems="center"
        >
          {" "}
          <Widgets title={"Users"} value={5} Icon={<PersonIcon />} />
          <Widgets title={"Chats"} value={25} Icon={<GroupIcon />} />
          <Widgets title={"Message"} value={2} Icon={<Message />} />{" "}
        </Stack>
      </Container>
    </AdminLayout>
  );
};

export default page;
